{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "javafmllanguage",
    "version": "1.20.1-47.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javafmllanguage-1.20.1-47.4.10.jar",
          "url": "javafmllanguage-1.20.1-47.4.10.jar",
          "size": 16854,
          "sha512": "c6f5eddab9ca7fd3412fcbf2e0f5671f36a56e6ad187796104a7dd600d2f6e0bfdf69d1633838ebb6b12894910ddb78ce65cdea1a4a2588d15aed50ea69ecba4",
          "sha256": "d3f6fb3c6e0a569ff475c1f5757406e5aa1ea956fd0c289bba361402b76e4232",
          "sha1": "ccc533c7dd67e0983217197d7549c8b49e7ab453",
          "md5": "1193446859d078e83d9fcc4d8a39f44d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.20.1-47.4.10"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "fmlcore",
          "version": {
            "requires": "1.20.1-47.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "javafmllanguage-1.20.1-47.4.10.jar",
          "url": "javafmllanguage-1.20.1-47.4.10.jar",
          "size": 16854,
          "sha512": "c6f5eddab9ca7fd3412fcbf2e0f5671f36a56e6ad187796104a7dd600d2f6e0bfdf69d1633838ebb6b12894910ddb78ce65cdea1a4a2588d15aed50ea69ecba4",
          "sha256": "d3f6fb3c6e0a569ff475c1f5757406e5aa1ea956fd0c289bba361402b76e4232",
          "sha1": "ccc533c7dd67e0983217197d7549c8b49e7ab453",
          "md5": "1193446859d078e83d9fcc4d8a39f44d"
        }
      ]
    }
  ]
}
